export const GET_USER_DATA = 'GET_USER_DATA';
export const SET_USER_DATA = 'SET_USER_DATA';
export const USER_NOT_FOUND = 'USER_NOT_FOUND';
export const USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS';
export const CLEAR_FORMS_ERRORS = 'CLEAR_FORMS_ERRORS';
